global:
  scrape_interval: 30s
  scrape_timeout: 1s

scrape_configs:
  # Prometheus metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          component: "prometheus"
  # RabbitMQ metrics
  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:15692']
        labels:
          component: "rabbitmq"
  # Host node metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          component: "node-exporter"
  # CAdvisor metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  # Application metrics as prometheus formatted
  - job_name: 'app_prometheus'
    metrics_path: '/prometheus'
    scrape_interval: 10s
    scrape_timeout: 2s
    static_configs:
      - targets: ['host.docker.internal:8090']
        labels:
          component: 'application'